FROM jrottenberg/ffmpeg

RUN apt-get update && \
    apt-get install python-dev python-pip -y && \
    apt-get clean

RUN pip install awscli
WORKDIR /root
COPY makeVideo.sh makeVideo.sh

ENTRYPOINT "/root/makeVideo.sh"