FROM jrottenberg/ffmpeg

RUN apt-get update && \
    apt-get install python-dev python-pip -y && \
    apt-get clean

RUN pip install awscli

COPY ./makeVideo.sh /root
CMD [ "bash", "-e" ]
ENTRYPOINT  ["/root/makeVideo.sh"]